repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: third_party|cpplint.py
      - id: end-of-file-fixer
        exclude: third_party|cpplint.py
      - id: check-docstring-first
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
    files: \.(c|cc|cxx|cpp|h|hpp|hxx|proto)$
